version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.9 
    working_directory: ~/repo

jobs:
  build-exe:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Instalar dependencias
          command: |
            sudo apt-get update
            sudo apt-get install -y upx
            python -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install pyinstaller
      - run:
          name: Generar el ejecutable
          command: |
            source venv/bin/activate
            pyinstaller --onefile --add-data "src:src" --upx-dir=/usr/bin/ src/Heroes_Del_Balon.py
            ls dist/
      - run:
          name: Mover el ejecutable al directorio raíz
          command: mv dist/Heroes_Del_Balon Heroes_Del_Balon.exe
      - persist_to_workspace:
          root: ~/repo
          paths:
            - Heroes_Del_Balon.exe

  deploy-to-repo:
    executor: python-executor
    steps:
      - checkout  # Clona el repositorio
      - attach_workspace:
          at: ~/repo  # Adjunta el ejecutable generado
      - run:
          name: Instalar dependencias
          command: |
            curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
            sudo apt-get install -y git-lfs
            git lfs install
      - run:
          name: Actualizar la rama local con los cambios remotos
          command: |
            git fetch origin main
            git pull origin main
      - run:
          name: Añadir el ejecutable al repositorio
          command: |
            git config --global user.email "87842940+hachazo@users.noreply.github.com"
            git config --global user.name "CircleCI Bot"
            git lfs track "*.exe"
            git add .gitattributes
            git commit -m "Configurar Git LFS"
            git add Heroes_Del_Balon.exe
            git commit -m "Añadido ejecutable generado por CircleCI con Git LFS"
            git push --force-with-lease origin main
workflows:
  build-and-deploy:
    jobs:
      - build-exe
      - deploy-to-repo:
          requires:
            - build-exe
