version: 2.1

executors:
  openwrt-build:
    docker:
      - image: debian:12  # Puedes cambiar a otra versión si es necesario
    working_directory: ~/openwrt

jobs:
  build:
    executor: openwrt-build
    steps:
      - checkout  # Clona el repositorio actual
      
      - run:
          name: Instalar dependencias
          command: |
            apt-get update && apt-get install -y \
              build-essential \
              clang \
              flex \
              bison \
              g++ \
              gawk \
              gcc-multilib \
              g++-multilib \
              gettext \
              git \
              libncurses-dev \
              libssl-dev \
              python3-distutils \
              python3-setuptools \
              rsync \
              swig \
              unzip \
              zlib1g-dev \
              file \
              libgl1-mesa-dev \
              libglu1-mesa-dev \
              libgraphene-1.0-dev \
              wget \
              libwayland-dev \
              libgraphene-1.0-0 \
              libgraphene-1.0-dev

      - run:
          name: Descargar código fuente de OpenWRT
          command: |
            git clone https://github.com/hachazo/openwrt_tlwr841hp_v2.git
            cd openwrt_tlwr841hp_v2/
            ./scripts/feeds update -a
            ./scripts/feeds install -a

       # # # # # # # # # # - run:
          # # # # # # # # # # name: configurar openwrt
          # # # # # # # # # # command: |
            # # # # # # # # # # cd openwrt_tlwr841hp_v2/
            # # # # # # # # # # make defconfig  # o usa `menuconfig` si necesitas personalizar la configuración

      - run:
          name: Compilar OpenWRT
          command: |
            cd openwrt_tlwr841hp_v2/
            #make oldconfig
            make -j$(nproc) tools/compile
            make -j$(nproc) V=s # Compila usando todos los núcleos disponibles

workflows:
  version: 2
  build-openwrt:
    jobs:
      - build
